config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, :only => [:show, :update]
  resources :categories do
      resources :tasks
    end

  root 'pages#home'
  get '/home' => 'pages#home'
  get '/profile' => 'pages#profile'
  get '/tasks' => 'pages#tasks'
  get '/search' => 'pages#search'
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks, :dependent => :destroy
    validates :category_name, presence: true
    ORDER_OPTIONS = [
        ['Alphabetical (Ascending)', 'item asc'], ['Alphabetical (Descending)', 'item desc'],
        ['First Created', 'created_at asc'], ['Last Created', 'created_at desc'],['Deadline (First)', 'deadline asc'], ['Deadline (Last)', 'deadline desc']
    ].freeze

    def badge_color
        case status
        when 'not-started'
            'danger'
        when 'in-progress'
            'warning'
        else 'completed'
            'success'
        end
    end

    def status
        return 'not-started' if tasks.none?
        #danger

        if tasks.all? { |task| task.complete? }
           return 'completed'
           #success
        elsif tasks.any? { |task| task.in_progress? || task.complete? }
            return 'in-progress'
            #warning
        else
            return 'not-started'
            #danger
        end
    end
    
    def percent_complete
        complete_tasks = tasks.select { |task| task.complete? }.count
        if complete_tasks == 0
            return 0
        end
        ((complete_tasks.to_f / tasks.count) * 100).round
    end

    def total_complete
        tasks.select { |task| task.complete? }.count
    end

    def total_tasks
        tasks.count
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories.paginate(page: params[:page], per_page: 5)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @task = @category.tasks.build
  end

  # GET /categories/new
  def new
    @category = current_user.categories.build
  end

  # GET /categories/1/edit
  def edit
    session[:return_to] ||= request.referer
  end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.build(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_tasks_path(@category), notice: "Journal was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    if @category.update(category_params)
      if @category.saved_change_to_attribute?("category_name") || @category.saved_change_to_attribute?("description")
        redirect_to session.delete(:return_to), notice: "Journal was successfully updated."
      elsif @category.saved_change_to_attribute?("order_by")
        redirect_to category_tasks_path(@category), notice: "Task sorting changed."
      else
        redirect_back(fallback_location: root_path)
      end
    else
      render action: 'edit'
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, alert: "Journal was deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = current_user.categories.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category_name, :description, :order_by)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
    def page_entries_info(collection, options = {})
        entry_name = options[:entry_name] || (collection.empty?? 'item' :
            collection.first.class.name.split('::').last.titleize).downcase
        if collection.total_pages < 2
          case collection.size
          when 0; "No journals found"
          when 1; "Displaying 1 #{entry_name}"
          else; "Displaying all #{@categories.count} #{entry_name.pluralize}"
          end
        else
          %{Displaying %d - %d of %d #{entry_name.pluralize}} % [
            collection.offset + 1,
            collection.offset + collection.length,
            collection.total_entries
          ]
        end
    end
end

app/views/categories/_category_card.html.erb
    <div class="card-body">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb fw-light mt-1">
                <li class="breadcrumb-item"><%= link_to 'Home', home_path, class: "text-decoration-none" %></li>
                <li class="breadcrumb-item active" aria-current="journals">Journals</li>
            </ol>
        </nav>

        <h1 class="card-title d-flex justify-content-between align-items-center mb-2 display-4 fw-normal">Journals
            <p class='mb-2'><%= link_to '+ New Journal', new_category_path, { class: 'btn btn-success btn-md py-1 px-2 shadow-sm rounded',  'data-bs-toggle'=> 'tooltip', 'data-bs-placement'=> 'bottom', 'title' => 'Create new journal' } %></p>
        </h1>
        <div class="d-flex flex-column flex-md-row justify-content-between align-items-center">
            <div class="text-center fw-light mb-md-4 mb-2 mt-md-2 mt-1 order-1 order-md-0">
                <%= page_entries_info @categories, :entry_name => 'journal' %>
            </div>
            <div class='order-0 order-md-1 mt-3 mt-md-0'>
            <% if @current_user.categories.count > 1 %>
                <%= form_for(@current_user) do |form| %>
                    <div class="col-12">
                        <div class="form-group mb-3 input-group input-group-sm">
                            <%= form.select :order_categories_by, User::ORDER_CATEGORY_OPTIONS, {}, class: 'form-control form-select shadow-sm rounded-start' %>
                            <%= form.submit 'Sort', class: 'btn btn-primary btn-sm shadow-sm', id: 'button-addon2' %>
                        </div>
                    </div>
                <% end %>
            <% end %>
            </div>
        </div>

        <% @categories.each_with_index do |category, index| %>
            <% if index > 3 %>
                <%= will_paginate @categories, list_classes: %w(pagination justify-content-center mt-2 px-0 btn-sm) %>
            <% end %>
        <% end %>
        
        <% @current_user.categories.order(@current_user.order_categories_by).paginate(page: params[:page], per_page: 5).each do |category| %>
            <% if category.persisted? %>
            <div class="card mb-4 category-card shadow-sm rounded">
                <div class="card-body">

                    <div class='d-flex justify-content-between'>
                    
                        <div class="progress w-25">
                            <div class="progress-bar bg-secondary" role="progressbar" style="width: <%= category.percent_complete %>%;" aria-valuenow="<%= category.percent_complete %>" aria-valuemin="0" aria-valuemax="100"><%= category.total_complete %> / <%= category.total_tasks %>
                            </div>
                        </div>
                        <small>
                            <%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_category_path(category), { class: 'btn btn-secondary btn-sm', 'data-bs-toggle' => 'tooltip', 'data-bs-placement' => 'bottom', 'title' => 'Edit journal' } %>
                            <%= link_to '<i class="bi bi-trash"></i>'.html_safe, category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm', 'data-bs-toggle' => 'tooltip', 'data-bs-placement' => 'bottom', 'title' => 'Delete journal' %>
                        </small>
                    </div>
                    
                    <div class="card-title d-flex justify-content-between align-items-start mb-0 mt-1">
                        <div class="d-flex align-items-start flex-column justify-content-start">
                            <span class="badge bg-<%= category.badge_color %> text-center mb-2"><%= category.status %> </span>
                            <p><%= link_to category.category_name, category_tasks_path(category), { class: 'text-decoration-none display-6 fw-normal', 'data-bs-toggle'=> 'tooltip', 'data-bs-placement'=> 'bottom', 'title' => 'View journal tasks' } %></p>
                        </div>
                        <small class='mt-1 text-muted'>Created: <%= category.created_at.strftime("%B %d, %Y") %></small>
                    </div>
                    <p class='mb-2 mt-0 text-secondary'><%= truncate(category.description, length: 80) %></p>
                </div>
            </div>
            <% end %>
        <% end %>

        <%= will_paginate @categories, list_classes: %w(pagination justify-content-center) %>
    </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>

  <%= render 'shared/errors', obj: @category%>

  <div class="form-group mb-3">
    <%= form.label :category_name, 'Name', class: 'mb-1'%>
    <%= form.text_field :category_name, class: 'form-control shadow-sm rounded', placeholder: 'Enter journal name', autofocus: true %>
  </div>

  <div class="form-group mt-2">
    <%= form.label :description, class: 'mb-1' %>
    <%= form.text_field :description, class: 'form-control shadow-sm rounded', placeholder: 'Optional' %>
  </div>

  <div class="actions mt-4 text-center">
    <%= form.submit 'Submit', class: 'btn btn-primary btn-md shadow rounded' %>
  </div>
  
<% end %>

app/views/categories/edit.html.erb
<div class="card mt-md-5 mt-3 shadow-lg rounded">
    <div class="card-body p-4">
        <h2 class="card-title mb-4">
            <span>Edit Journal</span>
        </h2>
        <%= render 'form', category: @category %>
    </div>
</div>

<div class="text-center mt-3">
    <%= link_to "Cancel", :back, class: 'mx-auto fw-light text-decoration-none' %>
</div>

app/views/categories/index.html.erb
<% if notice.present? %>
    <div class="alert alert-success text-center mt-3 mb-0" role="alert">
        <%= notice %>
    </div>
    <div class="card mt-3 shadow rounded">
    <%= render 'category_card' %>
<% elsif alert.present? %>
    <div class="alert alert-danger text-center mt-3 mb-0" role="alert">
        <%= alert %>
    </div>
    <div class="card mt-3 shadow rounded">
    <%= render 'category_card' %>
<% else %>
    <div class="card mt-md-4 mt-3 shadow rounded">
    <%= render 'category_card' %>
<% end %>

<div class="text-center mt-3 mb-4">
    <%= link_to 'Back to Home', home_path, class: 'fw-light text-decoration-none' %>
</div>

app/views/categories/new.html.erb
<div class="card mt-3 mt-md-5 shadow-lg rounded">
    <div class="card-body p-4">
        <h2 class="card-title mb-4">
            <span>New Journal</span>
        </h2>
        <%= render 'form', category: @category %>
    </div>
</div>

<div class="text-center mt-3">
    <%= link_to "Cancel", :back, class: 'mx-auto fw-light text-decoration-none' %>
</div>

app/views/categories/show.html.erb
<div class="card shadow rounded mt-md-5 mt-3">
  <div class="card-body">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb fw-light mb-4">
        <li class="breadcrumb-item" ><%= link_to 'Home', home_path, class: "text-decoration-none" %></li>
        <li class="breadcrumb-item"><%= link_to 'Journals', categories_path, class: "text-decoration-none" %></li>
        <li class="breadcrumb-item active" aria-current="tasks"><%= @category.category_name %></li>
      </ol>
    </nav>
      <h2 class="card-title d-flex justify-content-between mb-3 align-items-center">
      <span class='display-5 fw-normal'><%= @category.category_help_name %>
      <sup><small data-bs-toggle="tooltip" data-bs-placement="bottom" title="Edit journal"><%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_category_path(@category), class: 'text-muted', id: 'supIcon'%></small></sup><sup><small data-bs-toggle="tooltip" data-bs-placement="bottom" title="Delete journal"><%= link_to '<i class="bi bi-trash"></i>'.html_safe, @category, method: :delete, class: 'text-danger', id: 'supIcon', data: { confirm: 'Are you sure?' } %></small></sup></span>
      </h2>

      <div class="progress mb-4">
        <div class="progress-bar bg-secondary" role="progressbar" style="width: <%= @category.percent_complete %>%;" aria-valuenow="<%= @category.percent_complete %>" aria-valuemin="0" aria-valuemax="100"><%= @category.total_complete %> / <%= @category.total_tasks %>
        </div>
      </div>

      <div class="mb-4">
        <% if @category.description.present? %>
          <span class='fw-bold'>Description:</span> 
          <%= truncate(@category.description, length: 180) %>
        <% end %>
      </div>

      <hr class='my-4'>
      <div class='d-flex justify-content-between align-items-center mb-4 mb-lg-4'>
        <h4 class='display-6 fw-normal m-0'>Tasks</h4>
        <span>
          <%= link_to '+ New Task', new_category_task_path(@category), { class: 'btn btn-success text-center', 'data-bs-toggle'=> 'tooltip', 'data-bs-placement'=> 'bottom', 'title' => 'Create new task' } %>
        </span>
      </div>
              <p>Sort by: 
                <%= link_to "item", category_path(order: 'item') %>,
                <%= link_to "created_at", category_path(order: 'created_at') %>
              </p>
      <% @category.tasks.reverse_each do |task| %>
        <% if task.persisted? %>
          <div class="card mb-2 shadow-sm task-card">
            <div class="card-body py-2">
              <div class="d-flex justify-content-between align-items-center">
                <span class="badge mt-2 bg-<%= task.badge_color %> mb-2 text-center"><%= link_to task.status, edit_category_task_path(task.category, task), class: 'text-white text-decoration-none' %></span>
                <div class='my-2'>
                  <%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_category_task_path(task.category, task), { class: 'btn btn-secondary btn-sm', 'data-bs-toggle'=> 'tooltip', 'data-bs-placement'=> 'bottom', 'title' => 'Edit task' } %>
                  <%= link_to '<i class="bi bi-trash"></i>'.html_safe, [task.category, task], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm', 'data-bs-toggle'=> 'tooltip', 'data-bs-placement'=> 'bottom', 'title' => 'Delete task' %>
                </div>
              </div>
              
              <div class='d-flex justify-content-between col-12'>
                <h5 class="card-title mb-3">
                  <%= task.item %>  
                </h5>
                <div class='d-flex flex-column flex-md-row justify-content-start align-items-end mt-1 col-5 col-md-6 justify-content-md-end align-items-md-start'>
                  <small class='d-flex justify-content-end me-md-1'><%= link_to '<i class="bi bi-calendar-check"></i>'.html_safe, edit_category_task_path(task.category, task), class: 'text-decoration-none text-dark', id: 'calendarIcon' %></small>
                  <small data-bs-toggle="tooltip" data-bs-placement="bottom" title="Task deadline">
                  <% if task.deadline.present? %>
                    <%= link_to task.deadline.strftime("%B %d, %Y"), edit_category_task_path(task.category, task), class: 'text-decoration-none text-dark', id: 'addDeadline' %>
                  <% else %>
                    <%= link_to 'Add task deadline', edit_category_task_path(task.category, task), class: 'text-decoration-none text-dark', id: 'addDeadline' %>
                  <% end %>
                  </small>
                </div>
              </div>
              
              <p class="mb-2 text-secondary" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Task description"><%= truncate(task.description, length: 50) %></p>

            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="text-center mt-3 mb-5">
    <%= link_to 'Back to Journals', categories_path, class: 'fw-light text-decoration-none' %>
  </div>
</div>