config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, :only => [:show, :update]
  resources :categories do
      resources :tasks
    end

  root 'pages#home'
  get '/home' => 'pages#home'
  get '/profile' => 'pages#profile'
  get '/tasks' => 'pages#tasks'
  get '/search' => 'pages#search'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar sticky-top shadow-sm navbar-expand-sm navbar-dark px-4" style="background-color: #1a1a1a;">
  <div class="container-fluid">
     <%= link_to 'Dear Me <i class="bi bi-bookmarks"></i>'.html_safe, home_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
          <%= link_to "home", home_path, class: "nav-link text-light" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "journals", categories_path, class: "nav-link text-light" %>
            </li>
            <li class="nav-item">
              <%= link_to "profile", profile_path, class: "nav-link text-light" %>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "sign out", destroy_user_session_path, method: :delete, class: "nav-link text-light" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "log in", new_user_session_path, class: "nav-link text-light" %>
            </li>
            <li class="nav-item">
              <%= link_to "sign up", new_user_registration_path, class: "nav-link text-light" %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dear Me: Journaling Simplified</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="google-site-verification" content="nMtl0dpktqjYGIopfaZPpvvPth7F08VjAweJmijmHag" />
   
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@100;200;400;500&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <% if params[:action] == 'home' %>
      <%= yield %>
    <% else %>
      <div class="container col-lg-6">
        <%= yield %>
      </div>
    <% end %>
  </body>
</html>